/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void lengthOfRollArray(){
        Library rollArrayLength = new Library();

        //test the length of array depend in the number of roll is pass
        int[]output=Library.roll(4);
        assertEquals(4,output.length);
        assertEquals(true,Library.isBteween(output));

        //test the duplicate number in the array
        int[] containDuplicate= {1,2,3,4,5};
        int[] withoutContainDuplicate2= {1,2,3,3};
        int[] emptyArray= {};
        assertEquals(false,Library.containsDuplicates(containDuplicate));
        assertEquals(true,Library.containsDuplicates(withoutContainDuplicate2));
        assertEquals(false,Library.containsDuplicates(emptyArray));

        //test the average of the array
        int[] calculateAverageOfArray={10,20,50};
        int[] emptyArrayOfAverage={};
        assertEquals(26,(int)Library.calculateAverage(calculateAverageOfArray));
        assertEquals(0,(int) Library.calculateAverage(emptyArrayOfAverage));

        //test the minimum average
        int[][] arrOfArray = {{1,2,3},{1,0,1},{10,1,2}};
        int[][] ArrayOfArray1 = {{1,2,3},{4,5,6},{1,1,2}};
        assertEquals(arrOfArray[1],Library.lowestArray(arrOfArray));
        assertEquals(ArrayOfArray1[2],Library.lowestArray(ArrayOfArray1));
    }

}
