/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Library {

    public static void main(String[] args) {

        // create restaurant
        Restaurant restaurant1 = new Restaurant("kebab",5,50);
        Restaurant restaurant2 = new Restaurant("KFC",5,30);
        Restaurant restaurant3 = new Restaurant("Meat",4,20);

        System.out.println("restuarant1 before add review :"+ restaurant1);
        System.out.println("restuarant2 before add review :"+ restaurant2);
        System.out.println("restuarant3 before add review :"+ restaurant3);

        Review review1=new Review("I love kaba","Ali",1);
        Review review2=new Review("I love KFC","Ali",3);
        Review review3=new Review("I love Meat","Ali",2);

        restaurant1.addReview(review1);
        restaurant2.addReview(review2);
        restaurant3.addReview(review3);

        System.out.println();
        System.out.println("restuarant1 after add review :"+ restaurant1);
        System.out.println("restuarant2 after add review :"+ restaurant2);
        System.out.println("restuarant3 after add review :"+ restaurant3);

    }
}
