/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    @DisplayName("test many errors")
    public void manyError(){
        Path path = Paths.get("C:\\Users\\STUDENT\\Desktop\\401s\\java-fundamentals\\linter\\app\\src\\test\\resources\\gates.js");
        assertEquals(46,App.readFile(path.toString()).size());
    }
    @Test
    @DisplayName("test few errors")
    public void fewError(){
        Path path1 = Paths.get("C:\\Users\\STUDENT\\Desktop\\401s\\java-fundamentals\\linter\\app\\src\\test\\resources\\fewErrored.js");
        assertEquals(9,App.readFile(path1.toString()).size());
    }
    @Test
    @DisplayName("test one errors")
    public void oneError(){
        Path path1 = Paths.get("C:\\Users\\STUDENT\\Desktop\\401s\\java-fundamentals\\linter\\app\\src\\test\\resources\\oneError.js");
        assertEquals(1,App.readFile(path1.toString()).size(),"it should have one error");
    }
    @Test
    @DisplayName("test empty errors")
    public void emptyError(){
        Path path4 = Paths.get("C:\\Users\\STUDENT\\Desktop\\401s\\java-fundamentals\\linter\\app\\src\\test\\resources\\empty.js");
        System.out.println((path4.toString()));
        assertEquals(0,App.readFile(path4.toString()).size(),"it should have zero error");
    }
    @Test
    @DisplayName("test no errors")
    public void noError(){
        Path path4 = Paths.get("C:\\Users\\STUDENT\\Desktop\\401s\\java-fundamentals\\linter\\app\\src\\test\\resources\\noError.js");
        System.out.println((path4.toString()));
        assertEquals(0,App.readFile(path4.toString()).size(),"it should have no error");
    }

}
